spring.application.name=doctor-service
server.port=${PORT:8081}

spring.data.mongodb.uri=mongodb+srv://amritkrsharma018:amrit018@cluster0.jv1rthk.mongodb.net/
spring.data.mongodb.database=doctor

grpc.server.port=${GRPC_SERVER_PORT:9090}

