spring.security.oauth2.client.registration.keycloak-client.client-id=oath-amrit
spring.security.oauth2.client.registration.keycloak-client.client-secret=CNnzC95GiVByeJ5VY8lBJP90xDUoCMpB
spring.security.oauth2.client.registration.keycloak-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak-client.scope=openid

spring.security.oauth2.client.provider.keycloak-client.token-uri=http://localhost:8090/realms/healthcare/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8090/realms/healthcare
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/healthcare

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=doctor